### ISSUE TITLE
Not possible to adjust the calibration on ink bird via the UI

### ISSUE THREAD

**Issue by PoulKlemmensen** [thorrak/brewpi_esp_ui#4]
On e.g. Inkbird temperature sensors, it is not possible to adjust calibration when setting them up.

It seems like you have an error in AssignSensorModal.vue, line 280.

Think you have to change the following 
     device_definition.c = calibration_sendable;
to
     device_definition.j = calibration_sendable;

**Comment by thorrak** [comment]
Thank you - Fix will be incoming shortly!
